package com.aca56.cahiersortiecodex.ui.theme

import androidx.compose.ui.graphics.Color

val ForestGreenLight = Color(0xFF00684E)
val OnForestGreenLight = Color(0xFFFFFFFF)
val ForestGreenContainerLight = Color(0xFF8EF8CE)
val OnForestGreenContainerLight = Color(0xFF002117)

val ForestGreenDark = Color(0xFF6DDBB5)
val OnForestGreenDark = Color(0xFF003828)
val ForestGreenContainerDark = Color(0xFF00513D)
val OnForestGreenContainerDark = Color(0xFF8EF8CE)

val SecondaryGreenLight = Color(0xFF1F7A5E)
val OnSecondaryGreenLight = Color(0xFFFFFFFF)
val SecondaryGreenContainerLight = Color(0xFFA4EBCF)
val OnSecondaryGreenContainerLight = Color(0xFF002019)

val SecondaryGreenDark = Color(0xFF88D7B7)
val OnSecondaryGreenDark = Color(0xFF00382B)
val SecondaryGreenContainerDark = Color(0xFF00523F)
val OnSecondaryGreenContainerDark = Color(0xFFA4EBCF)

val TertiaryGreenLight = Color(0xFF2F8B68)
val OnTertiaryGreenLight = Color(0xFFFFFFFF)
val TertiaryGreenContainerLight = Color(0xFFB6F1D5)
val OnTertiaryGreenContainerLight = Color(0xFF002116)

val TertiaryGreenDark = Color(0xFF97DDBD)
val OnTertiaryGreenDark = Color(0xFF003826)
val TertiaryGreenContainerDark = Color(0xFF14513C)
val OnTertiaryContainerDark = Color(0xFFB6F1D5)

val AppBackgroundLight = Color(0xFFF3FBF7)
val AppOnBackgroundLight = Color(0xFF10201A)
val AppSurfaceLight = Color(0xFFF3FBF7)
val AppOnSurfaceLight = Color(0xFF10201A)
val AppSurfaceVariantLight = Color(0xFFD8E7DE)
val AppOnSurfaceVariantLight = Color(0xFF3D4D45)
val AppSurfaceDimLight = Color(0xFFD3E3DA)
val AppSurfaceBrightLight = Color(0xFFFAFDFB)
val AppSurfaceContainerLowestLight = Color(0xFFFFFFFF)
val AppSurfaceContainerLowLight = Color(0xFFEDF7F2)
val AppSurfaceContainerLight = Color(0xFFE7F2EC)
val AppSurfaceContainerHighLight = Color(0xFFE0ECE6)
val AppSurfaceContainerHighestLight = Color(0xFFDAE6E0)
val AppOutlineLight = Color(0xFF6D7D74)
val AppOutlineVariantLight = Color(0xFFBCCBC2)

val AppBackgroundDark = Color(0xFF09130F)
val AppOnBackgroundDark = Color(0xFFDCE8E1)
val AppSurfaceDark = Color(0xFF09130F)
val AppOnSurfaceDark = Color(0xFFDCE8E1)
val AppSurfaceVariantDark = Color(0xFF3D4D45)
val AppOnSurfaceVariantDark = Color(0xFFBCCBC2)
val AppSurfaceDimDark = Color(0xFF09130F)
val AppSurfaceBrightDark = Color(0xFF2C3833)
val AppSurfaceContainerLowestDark = Color(0xFF040B08)
val AppSurfaceContainerLowDark = Color(0xFF111B16)
val AppSurfaceContainerDark = Color(0xFF16211C)
val AppSurfaceContainerHighDark = Color(0xFF202B26)
val AppSurfaceContainerHighestDark = Color(0xFF2A3630)
val AppOutlineDark = Color(0xFF86968D)
val AppOutlineVariantDark = Color(0xFF3D4D45)

val AppErrorLight = Color(0xFFBA1A1A)
val AppOnErrorLight = Color(0xFFFFFFFF)
val AppErrorContainerLight = Color(0xFFFFDAD6)
val AppOnErrorContainerLight = Color(0xFF410002)

val AppErrorDark = Color(0xFFFFB4AB)
val AppOnErrorDark = Color(0xFF690005)
val AppErrorContainerDark = Color(0xFF93000A)
val AppOnErrorContainerDark = Color(0xFFFFDAD6)
